let products = [
    {
        "id": 1001,
        "title": "UI/UX",
        "description": "UI/UX is a very important subject for students that want to major in user interface and user experience.",
        "price": 5000,
        "location": "Dubai",
        "image": "images/product-uiux.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1002,
        "title": "Web Design",
        "description": "Web Design is very important for students that want to build web applications.",
        "price": 2500,
        "location": "Japan",
        "image": "images/product-web.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1003,
        "title": "Theatre",
        "description": "This course is crucial for actors to become pro actors.",
        "price": 3000,
        "location": "Tailand",
        "image": "images/product-theatre.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1004,
        "title": "Soccer",
        "description":  "We want to to help young stars have the ability to face the world.",
        "price": 8000,
        "location": "France",
        "image": "images/product-soccer.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1005,
        "title": "Music",
        "description":"We want to help young musicians and vocalists explore the world.",
        "price": 7000,
        "location": "Togo",
        "image": "images/product-music.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1006,
        "title": "Art",
        "description": "Art is very important for students .",
        "price": 4500,
        "location": "London",
        "image": "images/product-art.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1007,
        "title": "Science",
        "description": "Science is good for students to major in. We have teachers ready to take students.",
        "price": 6500,
        "location": "Germany",
        "image": "images/product-science.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1008,
        "title": "Spanish",
        "description": "Learning extra languages can be very helpful, Spanish is spoken in many countries, we would help you learn.",
        "price": 5000,
        "location": "Italy",
        "image": "images/product-spanish.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1009,
        "title": "Dancing",
        "description": "Dance is a performing art form consisting of purposefully selected sequences of human movement.",
        "price": 4500,
        "location": "China",
        "image": "images/product-dance.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 3000,
        "title": "Poultry",
        "description": "Poultry is any domesticated bird used for food, we want to teach you how to breed and take care of them.",
        "price": 2000,
        "location": "Lagos",
        "image": "images/product-poultry.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
]